import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy — ToolBrigade",
  description:
    "ToolBrigade's privacy policy. Your files never leave your device. Minimal anonymous analytics only.",
  alternates: { canonical: "https://toolbrigade.com/privacy" },
  openGraph: {
    title: "Privacy Policy — ToolBrigade",
    description: "Your files never leave your device. Minimal anonymous analytics only.",
    url: "https://toolbrigade.com/privacy",
    images: [{ url: "/og-image.png", width: 1200, height: 630, alt: "ToolBrigade Privacy Policy" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Privacy Policy — ToolBrigade",
    description: "Your files never leave your device. Minimal anonymous analytics only.",
    images: ["/og-image.png"],
  },
};

const lastUpdated = "2026";

export default function PrivacyPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-14">
      <nav className="text-sm text-[var(--text-muted)] mb-8 flex items-center gap-2">
        <Link href="/" className="hover:text-[var(--text)] transition-colors">Home</Link>
        <span>/</span>
        <span className="text-[var(--text)]">Privacy Policy</span>
      </nav>

      <div className="mb-10">
        <p className="section-label mb-3">Legal</p>
        <h1 className="font-display text-3xl md:text-4xl font-semibold text-[var(--text)] mb-3">Privacy Policy</h1>
        <p className="text-sm text-[var(--text-muted)]">Last updated: {lastUpdated}</p>
      </div>

      <div className="card bg-[var(--brand-light)] dark:bg-[var(--brand-light)]/60 border-brand-200 dark:border-brand-800 mb-10">
        <p className="text-sm text-brand-800 dark:text-brand-200 font-medium leading-relaxed">
          <strong>Short version:</strong> Every tool runs entirely in your browser. Your files, text, and data never leave your device. Only basic, anonymous analytics are collected to understand how the site is used.
        </p>
      </div>

      <div className="prose-custom space-y-10 text-[var(--text-muted)] leading-relaxed">

        <section>
          <h2 className="font-display text-lg font-semibold text-[var(--text)] mb-3">1. What ToolBrigade Is</h2>
          <p>
            ToolBrigade is a free browser-based tools site at <a href="https://toolbrigade.com" className="text-[var(--brand)] hover:underline">toolbrigade.com</a>, built and maintained by one developer.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-[var(--text)] mb-3">2. Data That Is NOT Collected</h2>
          <p className="mb-3">Because all tools run in your browser using JavaScript, the following is never collected, stored, or processed:</p>
          <ul className="space-y-2 list-none">
            {[
              "Any files you upload (images, PDFs, documents)",
              "Any text you type or paste into tools",
              "Any output generated by tools",
              "Personal information of any kind",
              "Account credentials (there are no accounts)",
            ].map((item) => (
              <li key={item} className="flex items-start gap-2 text-sm">
                <span className="text-brand-500 mt-0.5">✓</span>
                {item}
              </li>
            ))}
          </ul>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-[var(--text)] mb-3">3. Data That Is Collected</h2>
          <p className="mb-3">Minimal, anonymous data is collected to operate and improve the site:</p>
          <div className="space-y-4">
            <div className="card">
              <h3 className="font-semibold text-[var(--text)] mb-1 text-sm">Analytics</h3>
              <p className="text-sm">Anonymous usage analytics — page views, session duration, device type, and country. This data cannot identify you individually.</p>
            </div>
            <div className="card">
              <h3 className="font-semibold text-[var(--text)] mb-1 text-sm">Theme Cookie</h3>
              <p className="text-sm">Your theme preference (light/dark mode) is stored in a <code className="text-xs bg-[var(--bg-subtle)] px-1 py-0.5 rounded">theme</code> cookie. This data never leaves your device.</p>
            </div>
            <div className="card">
              <h3 className="font-semibold text-[var(--text)] mb-1 text-sm">Server Logs</h3>
              <p className="text-sm">The web server automatically logs standard HTTP request data (browser type, referring URL, timestamp). Logs are retained for up to 30 days for security purposes and are not shared with third parties.</p>
            </div>
          </div>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-[var(--text)] mb-3">4. Cookies</h2>
          <p>
            ToolBrigade uses minimal cookies. Analytics cookies are set to distinguish users and sessions. No advertising cookies, tracking pixels, or third-party marketing cookies are used. See the <Link href="/cookies" className="text-[var(--brand)] hover:underline">Cookie Policy</Link> for full details.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-[var(--text)] mb-3">5. Third-Party Services</h2>
          <p className="mb-3">The following third-party services are used:</p>
          <ul className="space-y-2 text-sm list-disc list-inside">
            <li><strong className="text-[var(--text)]">Analytics</strong> — anonymous usage data</li>
            <li><strong className="text-[var(--text)]">Hosting &amp; CDN</strong> — website delivery infrastructure</li>
            <li><strong className="text-[var(--text)]">Currency Rates API</strong> — live exchange rates for the Currency Converter tool only (no personal data sent)</li>
          </ul>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-[var(--text)] mb-3">6. Children&apos;s Privacy</h2>
          <p>
            ToolBrigade is not directed at children under 13. No personal information from children is knowingly collected. If you believe a child has provided personal information, contact me and it will be deleted promptly.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-[var(--text)] mb-3">7. Your Rights</h2>
          <p className="mb-3">
            Since minimal personal data is collected, there is little to request. However, you have the right to:
          </p>
          <ul className="space-y-1 text-sm list-disc list-inside">
            <li>Request information about what data is held about you</li>
            <li>Request deletion of any personal data held</li>
            <li>Opt out of analytics tracking</li>
          </ul>
          <p className="mt-3">To exercise these rights, contact <a href="mailto:privacy@toolbrigade.com" className="text-[var(--brand)] hover:underline">privacy@toolbrigade.com</a>.</p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-[var(--text)] mb-3">8. Changes to This Policy</h2>
          <p>
            This Privacy Policy may be updated from time to time. Significant changes will be reflected by updating the &ldquo;Last updated&rdquo; date at the top of this page. Continued use of ToolBrigade after changes constitutes acceptance of the updated policy.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-[var(--text)] mb-3">9. Contact</h2>
          <p>
            Questions about this Privacy Policy? Contact{" "}
            <a href="mailto:privacy@toolbrigade.com" className="text-[var(--brand)] hover:underline">
              privacy@toolbrigade.com
            </a>{" "}
            or visit the <Link href="/contact" className="text-[var(--brand)] hover:underline">Contact page</Link>.
          </p>
        </section>
      </div>
    </div>
  );
}
